const DatasDate = [
    "1770",
    "2063",
    "1901",
    "1940",
    "1770",
    "1917",
    "1008",
    "2065",
    "1384",
    "2025",
    "1989",
    "1709",
    "1402",
    "1111",
    "1423",
    "1296",
    "1897",
    "1731",
    "1188",
    "1423",
    "1296",
    "1897",
    "1731",
    "1188",
]
const Events = [
    "Presidential speech too long",
    "Ceiling of Baptist church collapses",
    "Famous band launches cereal",
    "Ferris wheel made of plastic",
    "King prawn abdicates",
    "Husband wears wife's perfume",
    "Opera via video link",
    "Sugar prohibited",
    "Blood donor loses blood",
    "Declaration declared intangible",
    "Aircraft carrier sinks",
    "New natural product found in dead-nettle",
    "Scroll found under parking lot",
    "Dynamite man marries gingerbread woman",
    "Chinese becomes world language",
    "Bus collides with rubbish cart",
    "3D stamp invented",
    "Celebrity is photographed",
    "New security designed for smartphones",
    "Chinese becomes world language",
    "Bus collides with rubbish cart",
    "3D stamp invented",
    "Celebrity is photographed",
    "New security designed for smartphones",
]


export {
    DatasDate, Events
}