import React, { useContext, useEffect, useState } from 'react';
const HomeContext = React.createContext(false)

export const HomeContextProvider = ({ children }) => {

    const [cursorW, setCursorW] = useState(JSON.parse(localStorage.getItem("cursorW")), 1)
    const [cursor, setCursor] = useState(0)
    const [numbers, setNumbers] = useState(
        [
            0,
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            0,
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            0,
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            0,
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            0,
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9, 0,
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9, 0,
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9, 0,
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9, 0,
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9, 0,
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9, 0,
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9, 0,
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9, 0,
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9, 0,
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9, 0,
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9, 0,
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9, 0,
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9, 0,
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
        ]
    )
    useEffect(() => {
        if (cursorW) {
            localStorage.setItem("cursorW", JSON.stringify(cursorW))
        }
    }, [cursorW])
    const value = {
        cursorW, setCursorW,
        numbers, setNumbers,
        cursor, setCursor
    }
    return (
        <HomeContext.Provider value={value}>
            {children}
        </HomeContext.Provider>
    );
}

export const useHomeContext = () => useContext(HomeContext)